<?php
/**
 * Mock Packages Data - 20 Sample Tours
 *
 * This file contains realistic tour package data for Peru tourism.
 * Organized by category: Day Tours, Multi-day Treks, Adventure, Combined Tours
 */

if (!defined('ABSPATH')) {
    exit;
}

return [
    // ========================================
    // DAY TOURS (1 day) - 8 tours
    // ========================================

    // 1. Machu Picchu Full Day Tour
    [
        'title' => 'Machu Picchu Full Day Tour',
        'data' => [
            'featured_package' => 1,
            'rating' => 4.8,
            'tripadvisor_rating' => 4.9,
            'total_reviews' => 2847,
            'tripadvisor_url' => 'https://www.tripadvisor.com/Attraction_Review-g294314-d12345678-Machu_Picchu_Full_Day_Tour-Cusco_Cusco_Region.html',
            'service_type' => 'shared',
            'summary' => 'Discover the iconic Lost City of the Incas on this unforgettable full-day adventure from Cusco, including train tickets, guided tour, and entrance fees.',
            'description' => '<p>Embark on an unforgettable journey to Machu Picchu, one of the New Seven Wonders of the World. This full-day tour takes you through the Sacred Valley aboard the comfortable Expedition train, offering breathtaking views of the Andean landscape.</p><p>Upon arrival at Aguas Calientes, you\'ll board a bus that climbs the winding road to the ancient citadel. Your expert guide will reveal the mysteries and history of this magnificent Inca site during a comprehensive 2-hour tour.</p><p>After the guided visit, enjoy free time to explore on your own, take photos, or hike to the Sun Gate for panoramic views.</p>',
            'included' => '<ul><li>Round-trip train tickets (Expedition class)</li><li>Bus tickets Aguas Calientes - Machu Picchu</li><li>Professional English/Spanish guide</li><li>Entrance fee to Machu Picchu</li><li>First aid kit and oxygen</li></ul>',
            'not_included' => '<ul><li>Meals and drinks</li><li>Travel insurance</li><li>Tips for guide and driver</li><li>Entrance to Huayna Picchu (optional, book in advance)</li></ul>',
            'highlight' => '<ul><li>Visit the iconic Machu Picchu citadel</li><li>Expert guided tour of the archaeological site</li><li>Scenic train journey through Sacred Valley</li><li>Free time to explore and take photos</li></ul>',
            'days' => 1,
            'duration' => '1 day (14 hours approx.)',
            'group_size' => 16,
            'activity_level' => 'moderate',
            'physical_difficulty' => 'moderate',
            'cultural_rating' => 5,
            'wildlife_expectation' => 2,
            'departure' => 'Ollantaytambo Train Station',
            'arrival' => 'Ollantaytambo Train Station',
            'departure_time' => '06:10 a.m.',
            'return_time' => '08:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 189,
            'price_normal' => 229,
            'price_offer' => 189,
            'per_person' => 1,
            'active_promotion' => 1,
            'promo_tag' => 'BEST SELLER',
            'promo_color' => '#ff6b6b',
            'meta_title' => 'Machu Picchu Full Day Tour from Cusco | Best Price Guaranteed',
            'meta_description' => 'Book your Machu Picchu full day tour with train tickets included. Expert guides, small groups, best prices. Available daily from Cusco.',
            'focus_keyword' => 'machu picchu tour',
            'show_on_homepage' => 1,

            // FASE 7 - Additional fields
            'google_rating' => 4.8,
            'tagline' => 'Discover the Lost City of the Incas',
            'show_rating_badge' => 1,
            'video_url' => 'https://www.youtube.com/watch?v=1Hqm9bS2gFw',
            'video_label' => 'Watch Our Machu Picchu Tour',
            'show_reserve_later' => 1,
            'show_international_standards' => 1,
            'is_prepayment' => 0,
            'optional' => 0,
            'travel_zoo' => 0,
            'show_specialist' => 1,
            'recommendations' => '<p>We highly recommend arriving in Cusco at least 2 days before this tour to acclimatize to the altitude. Bring a reusable water bottle and sunscreen. For the best experience, book during dry season (May-September).</p>',
            'price_single_supplement' => 75,
            'price_child' => 175,
            'available_months' => ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],
            'calendar_enabled' => 1,
            'important_notes' => '<p><strong>Important:</strong> Bring your original passport for entrance. Train tickets are non-refundable. Weather can change quickly in the mountains.</p>',
            'terms' => '<p>Full payment required at booking. Free cancellation up to 48 hours before departure. No refunds for no-shows.</p>',
            'seo_canonical' => '',
            'seo_robots' => 'index, follow',
            'seo_schema' => 'TouristAttraction',

            // FASE 2 - Missing fields
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Machu Picchu', 'Sacred Valley'],
            'inclusions' => [
                'Round-trip train tickets (Expedition class)',
                'Professional bilingual guide',
                'Entrance fee to Machu Picchu',
            ],
            'reviews' => [
                [
                    'author' => 'Sarah M.',
                    'rating' => 5,
                    'date' => '2025-09-15',
                    'content' => 'Absolutely incredible experience! Our guide was knowledgeable and the train journey was breathtaking. Machu Picchu exceeded all expectations.',
                    'country' => 'USA',
                ],
                [
                    'author' => 'James P.',
                    'rating' => 5,
                    'date' => '2025-08-22',
                    'content' => 'Well organized tour from start to finish. The guide brought the history to life and we had plenty of time to explore on our own.',
                    'country' => 'UK',
                ],
                [
                    'author' => 'Maria G.',
                    'rating' => 4,
                    'date' => '2025-07-10',
                    'content' => 'Great day trip! Only minor issue was the train was a bit delayed, but the overall experience was fantastic.',
                    'country' => 'Spain',
                ],
            ],

            // FASE 3
            'overview' => 'Experience the wonder of Machu Picchu, one of the New Seven Wonders of the World, on this comprehensive full-day tour from the Sacred Valley. Travel aboard the comfortable Expedition train through stunning Andean landscapes, then explore the ancient Inca citadel with an expert guide who will reveal its mysteries and history.',
            'quick_facts' => [
                ['icon' => 'clock', 'label' => 'Duration', 'value' => '14 hours'],
                ['icon' => 'users', 'label' => 'Group Size', 'value' => 'Max 16 people'],
                ['icon' => 'globe', 'label' => 'Languages', 'value' => 'English, Spanish'],
                ['icon' => 'calendar', 'label' => 'Availability', 'value' => 'Daily departures'],
            ],
            'highlights' => [
                'Scenic train journey through the Sacred Valley',
                'Guided tour of Machu Picchu citadel',
                'Temple of the Sun and Royal Palace',
                'Intihuatana Sun Stone',
                'Free time for photography and exploration',
            ],
            'itinerary' => [
                [
                    'day_number' => 1,
                    'title' => 'Machu Picchu Full Day Adventure',
                    'description' => 'Early morning pickup and transfer to Ollantaytambo train station. Board the Expedition train for a scenic 1.5-hour journey to Aguas Calientes. Take the bus up to Machu Picchu and enjoy a comprehensive 2-hour guided tour of the citadel. After the tour, free time to explore independently. Afternoon return by train to Ollantaytambo and transfer back to Cusco.',
                    'meals' => 'None (meals not included)',
                    'accommodation' => 'None (day tour)',
                    'activities' => ['Train journey', 'Guided tour of Machu Picchu', 'Free exploration time'],
                ],
            ],
            'brochure_url' => '',
            'guide_profiles' => [],

            // FASE 4
            'departures' => [
                ['date' => '2025-11-15', 'availability' => 'available', 'price' => 189, 'spaces_available' => 15, 'permits_left' => null],
                ['date' => '2025-11-22', 'availability' => 'available', 'price' => 189, 'spaces_available' => 12, 'permits_left' => null],
                ['date' => '2025-12-01', 'availability' => 'available', 'price' => 189, 'spaces_available' => 16, 'permits_left' => null],
                ['date' => '2025-12-15', 'availability' => 'limited', 'price' => 209, 'spaces_available' => 8, 'permits_left' => null],
            ],
            'inclusions_full' => [
                'Round-trip train tickets (Expedition class)',
                'Bus tickets Aguas Calientes - Machu Picchu - Aguas Calientes',
                'Professional English/Spanish bilingual guide',
                'Entrance fee to Machu Picchu citadel',
                'First aid kit and emergency oxygen',
                'Coordination and logistics support',
            ],
            'exclusions' => [
                'Meals and drinks',
                'Travel insurance',
                'Tips for guide and driver',
                'Entrance to Huayna Picchu mountain (optional, must book in advance)',
                'Personal expenses',
            ],
            'currency_options' => ['USD', 'EUR', 'GBP'],
            'show_price_calculator' => false,

            // FASE 5
            'contact_email' => 'info@peruviantours.com',
            'whatsapp_number' => '+51987654321',
            'contact_cta_text' => 'Book Your Machu Picchu Adventure Today!',
            'faqs' => [
                ['question' => 'What time does the tour start?', 'answer' => 'Pickup is at 6:10 AM from Ollantaytambo train station. We recommend arriving 30 minutes early.'],
                ['question' => 'Is altitude sickness a concern?', 'answer' => 'Machu Picchu is at 2,430m, lower than Cusco (3,400m), so altitude is less of a concern. We provide oxygen if needed.'],
                ['question' => 'Can I climb Huayna Picchu?', 'answer' => 'Huayna Picchu entrance is optional and must be booked separately in advance. Availability is limited to 400 people per day.'],
                ['question' => 'What should I bring?', 'answer' => 'Bring passport, comfortable walking shoes, sun protection, water bottle, camera, and light rain jacket.'],
            ],
            'review_platforms' => ['tripadvisor', 'google'],
            'show_review_filter' => true,

            // FASE 6
            'related_posts_manual' => [],
            'impact_title' => 'Sustainable Tourism & Local Communities',
            'impact_items' => [
                ['icon' => 'users', 'title' => 'Local Guides', 'description' => 'All our guides are certified locals who know the history and culture intimately'],
                ['icon' => 'leaf', 'title' => 'Eco-Friendly', 'description' => 'We practice responsible tourism and minimize environmental impact'],
                ['icon' => 'heart', 'title' => 'Community Support', 'description' => 'Portion of proceeds support local communities and preservation efforts'],
            ],
            'impact_background' => null,
            'trust_badges' => [
                ['logo_id' => null, 'name' => 'TripAdvisor Certificate of Excellence', 'url' => 'https://www.tripadvisor.com'],
                ['logo_id' => null, 'name' => 'Authorized Tour Operator', 'url' => ''],
            ],
            'certifications_text' => 'Global Standards, Local Heart - Certified by Peru Tourism Board',
        ],
        'taxonomies' => [
            'package_type' => ['Full Day Tour'],
            'interest' => ['Culture', 'History', 'Photography'],
            'locations' => ['Cusco', 'Machu Picchu'],
        ],
    ],

    // 2. Rainbow Mountain Trek
    [
        'title' => 'Rainbow Mountain (Vinicunca) Trek',
        'data' => [
            'featured_package' => 1,
            'rating' => 4.6,
            'tripadvisor_rating' => 4.7,
            'total_reviews' => 1893,
            'tripadvisor_url' => 'https://www.tripadvisor.com/Attraction_Review-g294314-d11223344-Rainbow_Mountain_Trek-Cusco_Cusco_Region.html',
            'service_type' => 'shared',
            'summary' => 'Trek to the stunning Rainbow Mountain at 5,200m altitude. Witness nature\'s colorful masterpiece with professional guides and small groups.',
            'description' => '<p>Experience one of Peru\'s most spectacular natural wonders on this challenging trek to Rainbow Mountain (Vinicunca). Located at 5,200 meters above sea level, this geological marvel displays vivid stripes of red, yellow, green, and turquoise minerals.</p><p>The trek takes approximately 3 hours uphill through stunning Andean landscapes, passing by local communities and herds of alpacas. Your expert guide will explain the geological formation and cultural significance of this sacred mountain.</p>',
            'included' => '<ul><li>Professional bilingual guide</li><li>Round-trip transportation</li><li>Breakfast and lunch (vegetarian options available)</li><li>Entrance fees</li><li>Oxygen and first aid kit</li><li>Walking sticks</li></ul>',
            'not_included' => '<ul><li>Snacks and extra drinks</li><li>Horse rental (optional - $20 USD)</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>See the incredible Rainbow Mountain stripes</li><li>Trek through remote Andean landscapes</li><li>Spot alpacas and llamas</li><li>Visit local communities</li><li>Views of Ausangate glacier</li></ul>',
            'days' => 1,
            'duration' => '1 day (12-14 hours)',
            'group_size' => 12,
            'activity_level' => 'very_high',
            'physical_difficulty' => 'difficult',
            'cultural_rating' => 3,
            'wildlife_expectation' => 4,
            'departure' => 'Cusco - Main Square',
            'arrival' => 'Cusco - Main Square',
            'departure_time' => '04:00 a.m.',
            'return_time' => '05:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 45,
            'price_normal' => 65,
            'price_offer' => 45,
            'per_person' => 1,
            'active_promotion' => 1,
            'promo_tag' => 'POPULAR',
            'promo_color' => '#4ecdc4',
            'meta_title' => 'Rainbow Mountain Trek Peru - Full Day Tour from Cusco',
            'meta_description' => 'Trek to the famous Rainbow Mountain (Vinicunca) at 5,200m. Professional guides, small groups, breakfast & lunch included.',
            'focus_keyword' => 'rainbow mountain trek',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Rainbow Mountain (Vinicunca)'],
            'inclusions' => [
                'Breakfast and lunch included',
                'Professional bilingual guide',
                'Oxygen and first aid kit',
            ],
            'reviews' => [
                [
                    'author' => 'Michael R.',
                    'rating' => 5,
                    'date' => '2025-08-18',
                    'content' => 'Challenging but absolutely worth it! The colors are even more vibrant in person. Our guide was excellent and very patient.',
                    'country' => 'Canada',
                ],
                [
                    'author' => 'Emma L.',
                    'rating' => 4,
                    'date' => '2025-07-25',
                    'content' => 'Beautiful mountain! The trek is tough due to altitude, but take it slow and you\'ll be fine. Breakfast was delicious.',
                    'country' => 'Australia',
                ],
            ],

            // FASE 3
            'overview' => 'Trek to one of Peru\'s most stunning natural wonders - Rainbow Mountain (Vinicunca). This challenging full-day adventure takes you to 5,200m altitude where you\'ll witness the incredible geological phenomenon of colorful mineral stripes painting the mountainside in vivid reds, yellows, greens, and turquoise.',
            'quick_facts' => [
                ['icon' => 'mountain', 'label' => 'Max Altitude', 'value' => '5,200m / 17,060ft'],
                ['icon' => 'clock', 'label' => 'Trek Duration', 'value' => '3 hours uphill'],
                ['icon' => 'users', 'label' => 'Group Size', 'value' => 'Max 12 people'],
                ['icon' => 'thermometer', 'label' => 'Temperature', 'value' => '-5°C to 10°C'],
            ],
            'highlights' => [
                'Colorful mineral stripes of Rainbow Mountain',
                'Views of Ausangate glacier (6,384m)',
                'Encounter with alpacas and llamas',
                'Remote Andean landscapes',
                'Local mountain communities',
            ],
            'itinerary' => [
                [
                    'day_number' => 1,
                    'title' => 'Rainbow Mountain Full Day Trek',
                    'description' => 'Early 4:00 AM pickup from Cusco. Drive 3 hours through Andean valleys to the trailhead. Enjoy breakfast at a local restaurant. Begin 3-hour uphill trek to Rainbow Mountain (5,200m), taking breaks to acclimatize. Reach the summit and marvel at the colorful stripes and Ausangate views. Descend 1.5 hours to trailhead. Lunch at local restaurant. Return drive to Cusco, arriving around 5:00 PM.',
                    'meals' => 'Breakfast, Lunch',
                    'accommodation' => 'None (day tour)',
                    'activities' => ['High-altitude trekking', 'Mountain photography', 'Wildlife spotting'],
                ],
            ],
            'brochure_url' => '',
            'guide_profiles' => [],

            // FASE 4
            'departures' => [
                ['date' => '2025-11-10', 'availability' => 'available', 'price' => 45, 'spaces_available' => 10, 'permits_left' => null],
                ['date' => '2025-11-17', 'availability' => 'available', 'price' => 45, 'spaces_available' => 12, 'permits_left' => null],
                ['date' => '2025-12-05', 'availability' => 'limited', 'price' => 55, 'spaces_available' => 8, 'permits_left' => null],
            ],
            'inclusions_full' => [
                'Professional bilingual mountain guide',
                'Round-trip transportation from Cusco',
                'Traditional Andean breakfast',
                'Buffet lunch with vegetarian options',
                'Entrance fees to Rainbow Mountain',
                'Oxygen cylinder and first aid kit',
                'Walking sticks (trekking poles)',
            ],
            'exclusions' => [
                'Snacks and extra beverages',
                'Horse rental (optional: $20-25 USD)',
                'Travel insurance',
                'Tips for guide and driver',
                'Personal expenses',
            ],
            'currency_options' => ['USD', 'EUR', 'GBP'],
            'show_price_calculator' => false,

            // FASE 5
            'contact_email' => 'info@peruviantours.com',
            'whatsapp_number' => '+51987654321',
            'contact_cta_text' => 'Book Your Rainbow Mountain Trek Now!',
            'faqs' => [
                ['question' => 'How difficult is this trek?', 'answer' => 'This is a challenging trek due to high altitude (5,200m). Good physical condition and prior acclimatization in Cusco (2-3 days) are essential.'],
                ['question' => 'Can I rent a horse?', 'answer' => 'Yes, horses are available to rent at the trailhead for $20-25 USD. They can take you most of the way up, with a short final walk to the summit.'],
                ['question' => 'What about altitude sickness?', 'answer' => 'We provide oxygen cylinders. It\'s crucial to spend 2-3 days in Cusco acclimatizing before this trek. Drink coca tea and take it slow.'],
                ['question' => 'What should I wear?', 'answer' => 'Dress in layers (thermal base, fleece, waterproof jacket), warm hat, gloves, sunglasses, sunscreen, and good hiking boots.'],
            ],
            'review_platforms' => ['tripadvisor', 'google'],
            'show_review_filter' => true,

            // FASE 6
            'related_posts_manual' => [],
            'impact_title' => 'Supporting Local Communities',
            'impact_items' => [
                ['icon' => 'users', 'title' => 'Local Communities', 'description' => 'Trek passes through indigenous communities who benefit from sustainable tourism'],
                ['icon' => 'horse', 'title' => 'Local Livelihoods', 'description' => 'Horse rentals provide income to local families'],
                ['icon' => 'leaf', 'title' => 'Environmental Care', 'description' => 'We practice Leave No Trace principles and minimize our environmental footprint'],
            ],
            'impact_background' => null,
            'trust_badges' => [
                ['logo_id' => null, 'name' => 'TripAdvisor Travelers Choice', 'url' => 'https://www.tripadvisor.com'],
                ['logo_id' => null, 'name' => 'Safe Travels Certified', 'url' => ''],
            ],
            'certifications_text' => 'Certified by Peru Ministry of Tourism - Responsible Mountain Tourism',
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Adventure'],
            'interest' => ['Nature', 'Photography', 'Adventure'],
            'locations' => ['Cusco', 'Vinicunca'],
        ],
    ],

    // 3. Sacred Valley Full Day Tour
    [
        'title' => 'Sacred Valley Full Day Tour',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.7,
            'tripadvisor_rating' => 4.6,
            'total_reviews' => 1567,
            'tripadvisor_url' => 'https://www.tripadvisor.com/Attraction_Review-g294314-d33445566-Sacred_Valley_Tour-Cusco_Cusco_Region.html',
            'service_type' => 'shared',
            'summary' => 'Explore the highlights of the Sacred Valley: Pisac Market, Ollantaytambo fortress, and Chinchero village in one comprehensive day tour.',
            'description' => '<p>Discover the breathtaking Sacred Valley of the Incas on this comprehensive full-day tour. Visit three of the most important archaeological sites and traditional villages in the Cusco region.</p><p>Begin at Pisac, famous for its vibrant artisan market and impressive Inca terraces. Continue to Ollantaytambo, a living Inca town with a magnificent temple fortress. End at Chinchero, known for its colonial church and traditional weaving demonstrations.</p>',
            'included' => '<ul><li>Professional guide (English/Spanish)</li><li>Round-trip transportation</li><li>Buffet lunch in Urubamba</li><li>Entrance fees to all sites</li></ul>',
            'not_included' => '<ul><li>Breakfast and dinner</li><li>Personal expenses</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Pisac archaeological site and market</li><li>Ollantaytambo fortress</li><li>Chinchero weaving demonstration</li><li>Buffet lunch with Andean specialties</li></ul>',
            'days' => 1,
            'duration' => '1 day (10 hours)',
            'group_size' => 20,
            'activity_level' => 'low',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 5,
            'wildlife_expectation' => 2,
            'departure' => 'Cusco - Plaza Regocijo',
            'arrival' => 'Cusco - Plaza Regocijo',
            'departure_time' => '08:00 a.m.',
            'return_time' => '06:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 35,
            'price_normal' => 50,
            'price_offer' => 35,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Sacred Valley Tour - Pisac, Ollantaytambo & Chinchero',
            'meta_description' => 'Full day Sacred Valley tour visiting Pisac, Ollantaytambo, and Chinchero. Buffet lunch included.',
            'focus_keyword' => 'sacred valley tour',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Sacred Valley', 'Pisac', 'Ollantaytambo'],
            'inclusions' => [
                'Buffet lunch in Urubamba',
                'Professional bilingual guide',
                'All entrance fees included',
            ],
            'reviews' => [
                [
                    'author' => 'Jennifer K.',
                    'rating' => 5,
                    'date' => '2025-09-03',
                    'content' => 'Perfect day exploring the Sacred Valley! Pisac market was amazing, and the lunch was delicious. Our guide was very knowledgeable.',
                    'country' => 'USA',
                ],
                [
                    'author' => 'Carlos R.',
                    'rating' => 4,
                    'date' => '2025-08-14',
                    'content' => 'Great overview of the valley. Ollantaytambo was the highlight for me. Only wish we had more time at each site.',
                    'country' => 'Mexico',
                ],
            ],

            // FASE 3
            'overview' => 'Discover the spectacular Sacred Valley of the Incas on this comprehensive full-day tour visiting the region\'s most important archaeological sites and traditional villages. From the vibrant Pisac market to the impressive Ollantaytambo fortress and the weaving traditions of Chinchero, experience the rich culture and history of the Inca Empire.',
            'quick_facts' => [
                ['icon' => 'map-marker', 'label' => 'Sites Visited', 'value' => 'Pisac, Ollantaytambo, Chinchero'],
                ['icon' => 'users', 'label' => 'Group Size', 'value' => 'Max 20 people'],
                ['icon' => 'clock', 'label' => 'Duration', 'value' => '10 hours'],
                ['icon' => 'shopping-cart', 'label' => 'Shopping', 'value' => 'Artisan markets'],
            ],
            'highlights' => [
                'Pisac archaeological site and artisan market',
                'Ollantaytambo living Inca town and fortress',
                'Chinchero traditional weaving demonstration',
                'Buffet lunch with Andean specialties',
                'Colonial churches and Inca architecture',
            ],
            'itinerary' => [
                [
                    'day_number' => 1,
                    'title' => 'Sacred Valley Highlights Tour',
                    'description' => '8:00 AM pickup from Cusco. Drive to Pisac to explore the archaeological site with terraces and temples, then visit the famous artisan market. Continue to Urubamba for buffet lunch featuring local cuisine. Visit Ollantaytambo fortress, a living Inca town with impressive stone structures. Final stop at Chinchero to see the colonial church built on Inca foundations and watch traditional textile demonstrations. Return to Cusco around 6:00 PM.',
                    'meals' => 'Buffet lunch',
                    'accommodation' => 'None (day tour)',
                    'activities' => ['Archaeological sites visit', 'Market shopping', 'Weaving demonstration', 'Cultural immersion'],
                ],
            ],
            'brochure_url' => '',
            'guide_profiles' => [],

            // FASE 4
            'departures' => [
                ['date' => '2025-11-12', 'availability' => 'available', 'price' => 35, 'spaces_available' => 18, 'permits_left' => null],
                ['date' => '2025-11-19', 'availability' => 'available', 'price' => 35, 'spaces_available' => 15, 'permits_left' => null],
                ['date' => '2025-12-03', 'availability' => 'available', 'price' => 40, 'spaces_available' => 12, 'permits_left' => null],
            ],
            'inclusions_full' => [
                'Professional English/Spanish bilingual guide',
                'Round-trip comfortable transportation',
                'Buffet lunch in Urubamba with Andean dishes',
                'Entrance fees to Pisac, Ollantaytambo, and Chinchero',
                'Weaving demonstration at Chinchero',
            ],
            'exclusions' => [
                'Breakfast and dinner',
                'Personal shopping expenses',
                'Tips for guide and driver',
                'Travel insurance',
            ],
            'currency_options' => ['USD', 'EUR', 'GBP'],
            'show_price_calculator' => false,

            // FASE 5
            'contact_email' => 'info@peruviantours.com',
            'whatsapp_number' => '+51987654321',
            'contact_cta_text' => 'Explore the Sacred Valley Today!',
            'faqs' => [
                ['question' => 'Is this tour suitable for families?', 'answer' => 'Yes! This is an easy tour with minimal walking, perfect for families with children and seniors.'],
                ['question' => 'How much time at Pisac market?', 'answer' => 'You\'ll have approximately 1 hour to shop at the artisan market and explore the handicrafts.'],
                ['question' => 'Can I buy handicrafts?', 'answer' => 'Yes, Pisac and Chinchero have excellent markets with alpaca products, textiles, ceramics, and souvenirs at fair prices.'],
                ['question' => 'What is included in the lunch?', 'answer' => 'Buffet includes traditional Peruvian dishes, international options, vegetarian choices, and soft drinks.'],
            ],
            'review_platforms' => ['tripadvisor', 'google'],
            'show_review_filter' => false,

            // FASE 6
            'related_posts_manual' => [],
            'impact_title' => 'Supporting Artisan Communities',
            'impact_items' => [
                ['icon' => 'users', 'title' => 'Local Artisans', 'description' => 'Purchases at markets directly support local weaving families and artisans'],
                ['icon' => 'palette', 'title' => 'Traditional Crafts', 'description' => 'We promote and preserve traditional weaving and pottery techniques'],
                ['icon' => 'heart', 'title' => 'Fair Trade', 'description' => 'We encourage fair prices for artisan work and cultural preservation'],
            ],
            'impact_background' => null,
            'trust_badges' => [
                ['logo_id' => null, 'name' => 'TripAdvisor Recommended', 'url' => 'https://www.tripadvisor.com'],
            ],
            'certifications_text' => 'Supporting Local Communities Through Responsible Tourism',
        ],
        'taxonomies' => [
            'package_type' => ['Full Day Tour', 'Cultural'],
            'interest' => ['Culture', 'History', 'Shopping'],
            'locations' => ['Sacred Valley', 'Pisac', 'Ollantaytambo', 'Chinchero'],
        ],
    ],

    // 4. Humantay Lake Trek
    [
        'title' => 'Humantay Lake Full Day Trek',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.5,
            'service_type' => 'shared',
            'summary' => 'Trek to the stunning turquoise Humantay Lake nestled at 4,200m beneath the Salkantay glacier.',
            'description' => '<p>Visit the stunning Humantay Lake, a hidden gem in the Andes known for its incredible turquoise waters. This challenging day trek takes you to 4,200 meters altitude, offering spectacular views of the Salkantay and Humantay glaciers.</p>',
            'included' => '<ul><li>Professional guide</li><li>Transportation from Cusco</li><li>Breakfast and lunch</li><li>Entrance fees</li><li>First aid kit and oxygen</li></ul>',
            'not_included' => '<ul><li>Horse rental (optional: $15-20)</li><li>Travel insurance</li><li>Tips</li><li>Extra drinks and snacks</li></ul>',
            'highlight' => '<ul><li>Turquoise Humantay Lake</li><li>Views of Salkantay glacier (6,271m)</li><li>High-altitude trekking experience</li><li>Traditional Andean breakfast</li></ul>',
            'days' => 1,
            'duration' => '1 day (12 hours)',
            'group_size' => 15,
            'activity_level' => 'high',
            'physical_difficulty' => 'moderate_demanding',
            'cultural_rating' => 2,
            'wildlife_expectation' => 3,
            'departure' => 'Cusco - Main Square',
            'arrival' => 'Cusco - Main Square',
            'departure_time' => '04:30 a.m.',
            'return_time' => '05:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 40,
            'price_normal' => 55,
            'price_offer' => 40,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Humantay Lake Trek - Full Day Tour from Cusco',
            'meta_description' => 'Trek to the beautiful Humantay Lake (4,200m) with turquoise waters and glacier views.',
            'focus_keyword' => 'humantay lake trek',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Humantay Lake'],
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Full Day Tour'],
            'interest' => ['Nature', 'Photography', 'Adventure'],
            'locations' => ['Cusco', 'Mollepata', 'Humantay'],
        ],
    ],

    // 5. Cusco City Tour
    [
        'title' => 'Cusco City Tour - Half Day',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.4,
            'service_type' => 'shared',
            'summary' => 'Discover the ancient capital of the Inca Empire. Visit Qorikancha, Sacsayhuaman, Q\'enqo, Puka Pukara, and Tambomachay.',
            'description' => '<p>Explore the fascinating city of Cusco and its nearby Inca ruins on this half-day tour. Start at the impressive Qorikancha (Temple of the Sun), where Inca stonework meets Spanish colonial architecture.</p><p>Continue to the massive fortress of Sacsayhuaman with its enormous stones, then visit the ceremonial center of Q\'enqo, the red fortress of Puka Pukara, and the water temple of Tambomachay.</p>',
            'included' => '<ul><li>Professional guide</li><li>Transportation</li><li>Entrance ticket to all sites</li></ul>',
            'not_included' => '<ul><li>Meals and drinks</li><li>Tips</li><li>Personal expenses</li></ul>',
            'highlight' => '<ul><li>Qorikancha Temple of the Sun</li><li>Sacsayhuaman fortress</li><li>Q\'enqo ceremonial center</li><li>Tambomachay water temple</li></ul>',
            'days' => 1,
            'duration' => 'Half day (4 hours)',
            'group_size' => 20,
            'activity_level' => 'low',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 5,
            'wildlife_expectation' => 1,
            'departure' => 'Cusco - Plaza de Armas',
            'arrival' => 'Cusco - Plaza de Armas',
            'departure_time' => '01:00 p.m.',
            'return_time' => '06:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 30,
            'price_normal' => 40,
            'price_offer' => 30,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Cusco City Tour - Half Day Archaeological Sites',
            'meta_description' => 'Explore Cusco and nearby Inca ruins: Sacsayhuaman, Qorikancha, Q\'enqo, Puka Pukara, Tambomachay.',
            'focus_keyword' => 'cusco city tour',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Cusco City Center'],
        ],
        'taxonomies' => [
            'package_type' => ['Full Day Tour', 'Cultural'],
            'interest' => ['Culture', 'History', 'Architecture'],
            'locations' => ['Cusco', 'Sacsayhuaman'],
        ],
    ],

    // 6. Maras & Moray Tour
    [
        'title' => 'Maras & Moray Half Day Tour',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.3,
            'service_type' => 'shared',
            'summary' => 'Visit the impressive Moray agricultural terraces and the ancient Maras salt mines in the Sacred Valley.',
            'description' => '<p>Explore two of the Sacred Valley\'s most unique sites on this half-day tour. Begin at Moray, an Inca agricultural laboratory with circular terraces creating different microclimates for crop experimentation.</p><p>Then visit the spectacular Maras salt mines, where thousands of salt pools cascade down the mountainside, still harvested using traditional Inca methods.</p>',
            'included' => '<ul><li>Professional guide</li><li>Transportation</li><li>Entrance fees</li></ul>',
            'not_included' => '<ul><li>Meals</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Moray circular agricultural terraces</li><li>Maras salt mines panoramic views</li><li>Learn about Inca agricultural techniques</li><li>Photo opportunities</li></ul>',
            'days' => 1,
            'duration' => 'Half day (5 hours)',
            'group_size' => 18,
            'activity_level' => 'low',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 4,
            'wildlife_expectation' => 1,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '08:00 a.m.',
            'return_time' => '01:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 32,
            'price_normal' => 45,
            'price_offer' => 32,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Maras & Moray Tour - Sacred Valley Salt Mines',
            'meta_description' => 'Visit Moray archaeological site and Maras salt mines. Half day tour from Cusco.',
            'focus_keyword' => 'maras moray tour',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Maras Salt Mines', 'Moray', 'Sacred Valley'],
        ],
        'taxonomies' => [
            'package_type' => ['Full Day Tour', 'Cultural'],
            'interest' => ['Culture', 'History', 'Photography'],
            'locations' => ['Sacred Valley', 'Maras', 'Moray'],
        ],
    ],

    // 7. South Valley Tour
    [
        'title' => 'South Valley Tour - Tipon, Pikillacta & Andahuaylillas',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.2,
            'service_type' => 'shared',
            'summary' => 'Discover the lesser-known South Valley with its Inca water channels, pre-Inca ruins, and the Sistine Chapel of the Americas.',
            'description' => '<p>Explore Cusco\'s beautiful South Valley on this full-day tour. Visit Tipon with its sophisticated Inca water channels and agricultural terraces, the pre-Inca walled city of Pikillacta, and the stunning baroque church of Andahuaylillas, known as the "Sistine Chapel of the Americas".</p>',
            'included' => '<ul><li>Professional guide</li><li>Transportation</li><li>Entrance fees to all sites</li><li>Lunch</li></ul>',
            'not_included' => '<ul><li>Breakfast and dinner</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Tipon water channels</li><li>Pikillacta pre-Inca ruins</li><li>Andahuaylillas baroque church</li><li>Less crowded alternative to Sacred Valley</li></ul>',
            'days' => 1,
            'duration' => '1 day (8 hours)',
            'group_size' => 16,
            'activity_level' => 'low',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 5,
            'wildlife_expectation' => 1,
            'departure' => 'Cusco - Plaza de Armas',
            'arrival' => 'Cusco - Plaza de Armas',
            'departure_time' => '09:00 a.m.',
            'return_time' => '05:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 38,
            'price_normal' => 50,
            'price_offer' => 38,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'South Valley Tour Cusco - Tipon, Pikillacta, Andahuaylillas',
            'meta_description' => 'Explore the South Valley of Cusco. Visit Tipon, Pikillacta, and the Sistine Chapel of the Americas.',
            'focus_keyword' => 'south valley cusco',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Cusco City Center'],
        ],
        'taxonomies' => [
            'package_type' => ['Full Day Tour', 'Cultural'],
            'interest' => ['Culture', 'History', 'Architecture'],
            'locations' => ['Cusco', 'Tipon', 'Pikillacta', 'Andahuaylillas'],
        ],
    ],

    // 8. Lake Titicaca Day Trip
    [
        'title' => 'Lake Titicaca Day Trip - Uros & Taquile Islands',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.5,
            'service_type' => 'shared',
            'summary' => 'Explore the floating reed islands of the Uros people and the traditional island of Taquile on beautiful Lake Titicaca.',
            'description' => '<p>Experience the highest navigable lake in the world on this full-day tour from Puno. Visit the incredible floating islands of the Uros, made entirely from totora reeds, and meet the friendly local communities.</p><p>Continue to Taquile Island, known for its textile art and traditional way of life. Enjoy panoramic lake views and a delicious lunch with local specialties.</p>',
            'included' => '<ul><li>Professional guide</li><li>Boat transportation</li><li>Lunch on Taquile Island</li><li>Entrance fees</li></ul>',
            'not_included' => '<ul><li>Breakfast and dinner</li><li>Tips</li><li>Transport Puno-Cusco</li></ul>',
            'highlight' => '<ul><li>Uros floating islands</li><li>Taquile Island and textiles</li><li>Traditional lunch</li><li>Stunning lake views</li></ul>',
            'days' => 1,
            'duration' => '1 day (9 hours)',
            'group_size' => 25,
            'activity_level' => 'low',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 5,
            'wildlife_expectation' => 3,
            'departure' => 'Puno - Lake Titicaca Port',
            'arrival' => 'Puno - Lake Titicaca Port',
            'departure_time' => '07:00 a.m.',
            'return_time' => '04:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 42,
            'price_normal' => 55,
            'price_offer' => 42,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Lake Titicaca Tour - Uros & Taquile Islands Day Trip',
            'meta_description' => 'Visit the floating Uros islands and Taquile Island on Lake Titicaca. Full day tour from Puno.',
            'focus_keyword' => 'lake titicaca tour',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Lake Titicaca'],
        ],
        'taxonomies' => [
            'package_type' => ['Full Day Tour', 'Cultural'],
            'interest' => ['Culture', 'Nature', 'Photography'],
            'locations' => ['Puno', 'Lake Titicaca', 'Uros', 'Taquile'],
        ],
    ],

    // ========================================
    // MULTI-DAY TREKS - 6 tours
    // ========================================

    // 9. Inca Trail 4 Days
    [
        'title' => 'Inca Trail 4 Days Trek to Machu Picchu',
        'data' => [
            'featured_package' => 1,
            'rating' => 4.9,
            'tripadvisor_rating' => 5.0,
            'total_reviews' => 4521,
            'tripadvisor_url' => 'https://www.tripadvisor.com/Attraction_Review-g294314-d98765432-Inca_Trail_4_Days-Cusco_Cusco_Region.html',
            'service_type' => 'private',
            'summary' => 'The classic 4-day Inca Trail trek to Machu Picchu. Experience ancient ruins, cloud forests, and arrive at the Sun Gate for sunrise.',
            'description' => '<p>Embark on the world\'s most famous trek: the Classic Inca Trail to Machu Picchu. This 4-day, 3-night adventure follows the original Inca pathway through stunning mountain passes, cloud forests, and numerous archaeological sites.</p><p>Hike along ancient stone pathways, cross high mountain passes at over 4,200m, and camp under the stars. On the final day, arrive at Inti Punku (Sun Gate) for sunrise views over Machu Picchu.</p>',
            'included' => '<ul><li>Professional bilingual guide and assistant</li><li>Camping equipment (tents, sleeping mats)</li><li>Porter service (7kg personal gear)</li><li>All meals during trek</li><li>Entrance fees: Inca Trail + Machu Picchu</li><li>Train ticket Aguas Calientes - Ollantaytambo</li><li>First aid kit and oxygen</li></ul>',
            'not_included' => '<ul><li>Sleeping bag (rental available: $20)</li><li>Walking poles (rental: $15)</li><li>Travel insurance (mandatory)</li><li>Tips for guide, cook, and porters</li></ul>',
            'highlight' => '<ul><li>Trek the legendary Inca Trail</li><li>Cross Dead Woman\'s Pass (4,215m)</li><li>Visit Wiñay Wayna ruins</li><li>Sunrise at Sun Gate over Machu Picchu</li><li>Small groups (max 12 people)</li></ul>',
            'days' => 4,
            'duration' => '4 days / 3 nights',
            'group_size' => 12,
            'activity_level' => 'very_high',
            'physical_difficulty' => 'very_difficult',
            'cultural_rating' => 5,
            'wildlife_expectation' => 4,
            'departure' => 'Cusco (Hotel pickup)',
            'arrival' => 'Cusco (Hotel drop-off)',
            'departure_time' => '05:00 a.m. (Day 1)',
            'return_time' => '08:00 p.m. (Day 4)',
            'spaces_available' => 'specific_dates',
            'price_from' => 650,
            'price_normal' => 750,
            'price_offer' => 650,
            'per_person' => 1,
            'active_promotion' => 1,
            'promo_tag' => 'EARLY BIRD',
            'promo_color' => '#feca57',
            'meta_title' => 'Inca Trail 4 Days to Machu Picchu - Classic Trek',
            'meta_description' => 'Book the classic 4-day Inca Trail trek to Machu Picchu. Expert guides, gourmet meals, small groups.',
            'focus_keyword' => 'inca trail 4 days',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Inca Trail', 'Machu Picchu'],
            'inclusions' => [
                'Premium camping equipment',
                'Gourmet meals during trek',
                'Expert bilingual guide',
            ],
            'reviews' => [
                [
                    'author' => 'Robert H.',
                    'rating' => 5,
                    'date' => '2025-08-05',
                    'content' => 'The experience of a lifetime! Our guide was phenomenal, the food exceeded expectations, and arriving at the Sun Gate at sunrise was magical. Highly recommend!',
                    'country' => 'USA',
                ],
                [
                    'author' => 'Sophie L.',
                    'rating' => 5,
                    'date' => '2025-07-18',
                    'content' => 'Challenging but incredible trek. The ruins along the way were amazing. Porters and cook team were so professional. Worth every penny!',
                    'country' => 'France',
                ],
                [
                    'author' => 'David K.',
                    'rating' => 5,
                    'date' => '2025-06-22',
                    'content' => 'Best adventure ever! Dead Woman\'s Pass was tough but the views made it worthwhile. Small group size was perfect.',
                    'country' => 'Australia',
                ],
            ],

            // FASE 3
            'overview' => 'Experience the world\'s most famous trek on the Classic Inca Trail to Machu Picchu. This 4-day, 3-night adventure follows the original Inca stone pathways through stunning mountain passes, mystical cloud forests, and fascinating archaeological sites, culminating in a magical sunrise arrival at the Sun Gate overlooking Machu Picchu.',
            'quick_facts' => [
                ['icon' => 'mountain', 'label' => 'Highest Point', 'value' => 'Dead Woman\'s Pass - 4,215m'],
                ['icon' => 'route', 'label' => 'Distance', 'value' => '43km (26 miles)'],
                ['icon' => 'users', 'label' => 'Group Size', 'value' => 'Max 12 trekkers'],
                ['icon' => 'calendar', 'label' => 'Permit Required', 'value' => 'Book 6+ months ahead'],
            ],
            'highlights' => [
                'Trek the legendary Inca Trail stone pathways',
                'Cross Dead Woman\'s Pass at 4,215m',
                'Visit Wiñay Wayna and Phuyupatamarca ruins',
                'Enter Machu Picchu through the Sun Gate at sunrise',
                'Gourmet meals prepared by professional trek chef',
                'Small group size with expert bilingual guide',
            ],
            'itinerary' => [
                [
                    'day_number' => 1,
                    'title' => 'Cusco to Wayllabamba Camp',
                    'description' => 'Early pickup from Cusco hotel. Drive to Km 82 to begin trek. Hike through Andean valleys with views of Veronica Mountain. Visit Llactapata archaeological site. Ascend gradually to Wayllabamba camp (3,000m). Total hiking: 12km, 6-7 hours.',
                    'meals' => 'Lunch, Dinner',
                    'accommodation' => 'Camping (tents provided)',
                    'activities' => ['Trekking', 'Archaeological site visit', 'Mountain views'],
                ],
                [
                    'day_number' => 2,
                    'title' => 'Wayllabamba to Pacaymayo Camp',
                    'description' => 'Most challenging day. Steep ascent through cloud forest to Dead Woman\'s Pass (4,215m), the highest point of the trek. Descend to Pacaymayo valley (3,600m) for camp. Total hiking: 11km, 7-8 hours.',
                    'meals' => 'Breakfast, Lunch, Dinner',
                    'accommodation' => 'Camping (tents provided)',
                    'activities' => ['High-altitude trekking', 'Cloud forest', 'Mountain pass crossing'],
                ],
                [
                    'day_number' => 3,
                    'title' => 'Pacaymayo to Wiñay Wayna Camp',
                    'description' => 'Cross two more passes: Runkurakay (3,970m) and Phuyupatamarca (3,650m). Visit impressive archaeological sites including circular Runkurakay and terraced Sayacmarca. Descend through cloud forest to Wiñay Wayna ruins and camp (2,650m). Total hiking: 16km, 8-9 hours.',
                    'meals' => 'Breakfast, Lunch, Dinner',
                    'accommodation' => 'Camping (tents provided)',
                    'activities' => ['Multiple archaeological sites', 'Cloud forest descent', 'Inca stone pathways'],
                ],
                [
                    'day_number' => 4,
                    'title' => 'Wiñay Wayna to Machu Picchu to Cusco',
                    'description' => '3:30 AM wake up for final trek to Sun Gate (Inti Punku) to watch sunrise over Machu Picchu. Descend to the citadel for 2-hour guided tour. Afternoon train to Ollantaytambo and transfer back to Cusco hotel. Total hiking: 6km, 2 hours.',
                    'meals' => 'Breakfast, Lunch',
                    'accommodation' => 'None (return to Cusco)',
                    'activities' => ['Sunrise at Sun Gate', 'Machu Picchu guided tour', 'Train journey'],
                ],
            ],
            'brochure_url' => '',
            'guide_profiles' => [],

            // FASE 4
            'departures' => [
                ['date' => '2026-05-15', 'availability' => 'available', 'price' => 650, 'spaces_available' => 8, 'permits_left' => 8],
                ['date' => '2026-06-01', 'availability' => 'available', 'price' => 650, 'spaces_available' => 10, 'permits_left' => 10],
                ['date' => '2026-07-10', 'availability' => 'limited', 'price' => 720, 'spaces_available' => 4, 'permits_left' => 4],
                ['date' => '2026-08-15', 'availability' => 'sold_out', 'price' => 720, 'spaces_available' => 0, 'permits_left' => 0],
            ],
            'inclusions_full' => [
                'Professional bilingual guide and assistant guide',
                'Premium 4-season camping equipment (tents, sleeping mats)',
                'Porter service for 7kg personal gear per person',
                'All meals during trek (breakfast, lunch, dinner, snacks)',
                'Gourmet meals prepared by professional trek chef',
                'Inca Trail entrance permit',
                'Machu Picchu entrance fee (Circuit 1 or 2)',
                'Train ticket Aguas Calientes to Ollantaytambo',
                'Bus ticket Machu Picchu to Aguas Calientes',
                'First aid kit and emergency oxygen',
                'Satellite phone for emergencies',
            ],
            'exclusions' => [
                'Sleeping bag (rental available: $20)',
                'Walking poles/trekking poles (rental: $15 per pair)',
                'Travel insurance (mandatory for this trek)',
                'Tips for guide, assistant guide, cook, and porters',
                'First day breakfast and last day dinner',
                'Personal expenses',
            ],
            'currency_options' => ['USD', 'EUR', 'GBP'],
            'show_price_calculator' => true,

            // FASE 5
            'contact_email' => 'info@peruviantours.com',
            'whatsapp_number' => '+51987654321',
            'contact_cta_text' => 'Book Your Inca Trail Adventure - Limited Permits!',
            'faqs' => [
                ['question' => 'How far in advance should I book?', 'answer' => 'Inca Trail permits sell out 6+ months in advance, especially for May-August. We recommend booking as early as possible.'],
                ['question' => 'What fitness level is required?', 'answer' => 'Good physical fitness is essential. You should be able to hike 6-8 hours per day at altitude. Training with cardio and hill walking is recommended.'],
                ['question' => 'Can I bring a larger backpack?', 'answer' => 'Porters carry 7kg of your personal gear. You carry a daypack with water, camera, snacks, and rain gear. Main duffelbag is transported by porters.'],
                ['question' => 'What if I can\'t get a permit?', 'answer' => 'If permits are sold out, we offer alternative treks like Salkantay (5 days) or Short Inca Trail (2 days) that don\'t require permits as far in advance.'],
                ['question' => 'Are meals really gourmet?', 'answer' => 'Yes! Our professional chef prepares fresh, delicious 3-course meals including vegetarian options. Many trekkers are amazed by the quality.'],
            ],
            'review_platforms' => ['tripadvisor', 'google'],
            'show_review_filter' => true,

            // FASE 6
            'related_posts_manual' => [],
            'impact_title' => 'Responsible Trekking & Porter Welfare',
            'impact_items' => [
                ['icon' => 'users', 'title' => 'Fair Porter Wages', 'description' => 'We exceed minimum wage requirements and provide proper equipment for all porters'],
                ['icon' => 'shield', 'title' => 'Porter Protection', 'description' => 'Weight limits strictly enforced, insurance provided, and health monitored daily'],
                ['icon' => 'leaf', 'title' => 'Leave No Trace', 'description' => 'All waste packed out, toilets provided, and environmental impact minimized'],
            ],
            'impact_background' => null,
            'trust_badges' => [
                ['logo_id' => null, 'name' => 'TripAdvisor Certificate of Excellence', 'url' => 'https://www.tripadvisor.com'],
                ['logo_id' => null, 'name' => 'Authorized Inca Trail Operator', 'url' => ''],
                ['logo_id' => null, 'name' => 'IPPG Member (International Porter Protection Group)', 'url' => ''],
            ],
            'certifications_text' => 'Certified by Peru Ministry of Culture - Committed to Porter Welfare and Sustainable Tourism',
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Multi-day'],
            'interest' => ['Adventure', 'Nature', 'History', 'Photography'],
            'locations' => ['Cusco', 'Inca Trail', 'Machu Picchu'],
        ],
    ],

    // 10. Salkantay Trek 5 Days
    [
        'title' => 'Salkantay Trek 5 Days to Machu Picchu',
        'data' => [
            'featured_package' => 1,
            'rating' => 4.7,
            'tripadvisor_rating' => 4.8,
            'total_reviews' => 3214,
            'tripadvisor_url' => 'https://www.tripadvisor.com/Attraction_Review-g294314-d55667788-Salkantay_Trek_5_Days-Cusco_Cusco_Region.html',
            'service_type' => 'shared',
            'summary' => 'Trek through diverse landscapes from snow-capped peaks to tropical jungle on this stunning alternative to the Inca Trail.',
            'description' => '<p>The Salkantay Trek is considered one of the top 25 treks in the world by National Geographic. This 5-day adventure takes you through diverse ecosystems, from high-altitude mountain passes at 4,650m to lush cloud forests.</p><p>Experience breathtaking views of Salkantay Mountain (6,271m), camp under the stars, bathe in hot springs, and arrive at Machu Picchu via the scenic town of Aguas Calientes.</p>',
            'included' => '<ul><li>Professional guide</li><li>All camping equipment</li><li>Porter service</li><li>All meals during trek</li><li>Hot springs entrance</li><li>Train ticket to Machu Picchu</li><li>Machu Picchu entrance fee and guided tour</li></ul>',
            'not_included' => '<ul><li>Sleeping bag (rental: $20)</li><li>First and last meals</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Cross Salkantay Pass (4,650m)</li><li>Views of Salkantay and Humantay peaks</li><li>Cloud forest and jungle scenery</li><li>Santa Teresa hot springs</li><li>Machu Picchu guided tour</li></ul>',
            'days' => 5,
            'duration' => '5 days / 4 nights',
            'group_size' => 14,
            'activity_level' => 'very_high',
            'physical_difficulty' => 'very_difficult',
            'cultural_rating' => 4,
            'wildlife_expectation' => 4,
            'departure' => 'Cusco - Main Square',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '04:30 a.m. (Day 1)',
            'return_time' => '09:00 p.m. (Day 5)',
            'spaces_available' => 'daily',
            'price_from' => 380,
            'price_normal' => 450,
            'price_offer' => 380,
            'per_person' => 1,
            'active_promotion' => 1,
            'promo_tag' => 'ADVENTURE',
            'promo_color' => '#ff9f43',
            'meta_title' => 'Salkantay Trek 5 Days to Machu Picchu - Best Route',
            'meta_description' => 'Trek the spectacular Salkantay route to Machu Picchu. 5 days through mountains, jungle, and hot springs.',
            'focus_keyword' => 'salkantay trek',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Salkantay Mountain', 'Machu Picchu'],
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Multi-day', 'Adventure'],
            'interest' => ['Adventure', 'Nature', 'Photography'],
            'locations' => ['Cusco', 'Salkantay', 'Machu Picchu', 'Santa Teresa'],
        ],
    ],

    // 11. Ausangate Trek 6 Days
    [
        'title' => 'Ausangate Trek 6 Days - Rainbow Mountain Circuit',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.8,
            'service_type' => 'private',
            'summary' => 'Trek around the sacred Ausangate Mountain (6,384m), visiting Rainbow Mountain, turquoise lakes, and remote Andean communities.',
            'description' => '<p>The Ausangate Trek is one of Peru\'s most spectacular and challenging high-altitude treks. Circle the sacred Ausangate Mountain, the highest peak in the Cusco region, passing through dramatic landscapes with turquoise glacial lakes, hot springs, and herds of alpacas.</p><p>This trek includes Rainbow Mountain as part of the circuit, offering a more authentic and less crowded experience than the day tour.</p>',
            'included' => '<ul><li>Expert mountain guide</li><li>Camping equipment</li><li>Pack horses for equipment</li><li>All meals during trek</li><li>Emergency horse</li><li>First aid kit and oxygen</li></ul>',
            'not_included' => '<ul><li>Sleeping bag</li><li>Personal items</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Circle the sacred Ausangate (6,384m)</li><li>Rainbow Mountain without crowds</li><li>Turquoise glacial lakes</li><li>Natural hot springs</li><li>High passes over 5,000m</li></ul>',
            'days' => 6,
            'duration' => '6 days / 5 nights',
            'group_size' => 10,
            'activity_level' => 'very_high',
            'physical_difficulty' => 'very_difficult',
            'cultural_rating' => 3,
            'wildlife_expectation' => 5,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '04:00 a.m. (Day 1)',
            'return_time' => '06:00 p.m. (Day 6)',
            'spaces_available' => 'specific_dates',
            'price_from' => 580,
            'price_normal' => 680,
            'price_offer' => 580,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Ausangate Trek 6 Days - Rainbow Mountain Circuit Peru',
            'meta_description' => 'Trek around sacred Ausangate Mountain. Visit Rainbow Mountain, glacial lakes, and hot springs.',
            'focus_keyword' => 'ausangate trek',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Ausangate Mountain', 'Rainbow Mountain (Vinicunca)'],
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Multi-day', 'Adventure'],
            'interest' => ['Adventure', 'Nature', 'Photography', 'Wildlife'],
            'locations' => ['Cusco', 'Ausangate', 'Vinicunca'],
        ],
    ],

    // 12. Lares Trek 4 Days
    [
        'title' => 'Lares Trek 4 Days to Machu Picchu',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.6,
            'service_type' => 'shared',
            'summary' => 'Experience authentic Andean culture on the Lares Trek, visiting remote villages, hot springs, and ending at Machu Picchu.',
            'description' => '<p>The Lares Trek offers a unique cultural experience, passing through traditional Andean villages where locals maintain their ancestral way of life. Trek through stunning mountain scenery, cross high passes, and soak in natural hot springs.</p><p>This route focuses on cultural immersion, with opportunities to interact with local weavers and farmers before taking the train to Machu Picchu.</p>',
            'included' => '<ul><li>Bilingual guide</li><li>Camping equipment</li><li>Pack horses</li><li>All meals during trek</li><li>Hot springs entrance</li><li>Train to Aguas Calientes</li><li>Machu Picchu entrance and tour</li></ul>',
            'not_included' => '<ul><li>Sleeping bag</li><li>First and last meals</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Visit authentic Andean villages</li><li>Lares hot springs</li><li>Traditional weaving demonstrations</li><li>Scenic mountain passes</li><li>Machu Picchu guided tour</li></ul>',
            'days' => 4,
            'duration' => '4 days / 3 nights',
            'group_size' => 14,
            'activity_level' => 'high',
            'physical_difficulty' => 'moderate_demanding',
            'cultural_rating' => 5,
            'wildlife_expectation' => 3,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '05:00 a.m. (Day 1)',
            'return_time' => '08:00 p.m. (Day 4)',
            'spaces_available' => 'daily',
            'price_from' => 480,
            'price_normal' => 560,
            'price_offer' => 480,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Lares Trek 4 Days to Machu Picchu - Cultural Route',
            'meta_description' => 'Trek the Lares Valley visiting Andean villages, hot springs, and Machu Picchu. Cultural immersion.',
            'focus_keyword' => 'lares trek',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Lares Valley', 'Machu Picchu'],
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Multi-day', 'Cultural'],
            'interest' => ['Culture', 'Adventure', 'Photography'],
            'locations' => ['Cusco', 'Lares', 'Machu Picchu'],
        ],
    ],

    // 13. Choquequirao Trek 4 Days
    [
        'title' => 'Choquequirao Trek 4 Days - Sister of Machu Picchu',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.7,
            'service_type' => 'private',
            'summary' => 'Trek to the remote Choquequirao ruins, Machu Picchu\'s sister city, with only 1% of its visitors but equal grandeur.',
            'description' => '<p>Choquequirao (Cradle of Gold) is a spectacular Inca site that receives a fraction of Machu Picchu\'s visitors. This challenging trek descends into the Apurimac Canyon and climbs to the remote ruins perched at 3,050m.</p><p>Only 30% of the site has been excavated, making it a true adventure for those seeking an off-the-beaten-path experience.</p>',
            'included' => '<ul><li>Expert guide</li><li>Camping equipment</li><li>Pack mules</li><li>All meals</li><li>Entrance fees</li><li>First aid kit</li></ul>',
            'not_included' => '<ul><li>Sleeping bag</li><li>Personal items</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Remote Choquequirao ruins</li><li>Apurimac Canyon views</li><li>Few tourists - authentic experience</li><li>Condor watching opportunities</li><li>Challenging and rewarding trek</li></ul>',
            'days' => 4,
            'duration' => '4 days / 3 nights',
            'group_size' => 8,
            'activity_level' => 'very_high',
            'physical_difficulty' => 'very_difficult',
            'cultural_rating' => 5,
            'wildlife_expectation' => 4,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '05:00 a.m. (Day 1)',
            'return_time' => '08:00 p.m. (Day 4)',
            'spaces_available' => 'on_request',
            'price_from' => 520,
            'price_normal' => 620,
            'price_offer' => 520,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Choquequirao Trek 4 Days - Sister of Machu Picchu',
            'meta_description' => 'Trek to remote Choquequirao ruins. Challenging 4-day adventure to the sister city of Machu Picchu.',
            'focus_keyword' => 'choquequirao trek',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Choquequirao', 'Machu Picchu'],
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Multi-day', 'Adventure'],
            'interest' => ['Adventure', 'History', 'Nature', 'Wildlife'],
            'locations' => ['Cusco', 'Choquequirao', 'Apurimac'],
        ],
    ],

    // 14. Inca Trail Short 2 Days
    [
        'title' => 'Short Inca Trail 2 Days to Machu Picchu',
        'data' => [
            'featured_package' => 1,
            'rating' => 4.5,
            'service_type' => 'shared',
            'summary' => 'Experience the magic of the Inca Trail in just 2 days. Perfect for those with limited time who still want to hike to Machu Picchu.',
            'description' => '<p>The Short Inca Trail is perfect for travelers who want to experience hiking the Inca Trail but have limited time. This 2-day trek covers the final and most scenic section of the Classic Inca Trail.</p><p>Hike through cloud forest, visit the impressive Wiñay Wayna ruins, and arrive at Machu Picchu through the Sun Gate, just like the longer trek.</p>',
            'included' => '<ul><li>Professional guide</li><li>Train to Km 104</li><li>Camping equipment (Day 1)</li><li>All meals during trek</li><li>Entrance: Inca Trail + Machu Picchu (2 days)</li><li>Hotel in Aguas Calientes (1 night)</li><li>Return train to Ollantaytambo</li></ul>',
            'not_included' => '<ul><li>First breakfast and last dinner</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Hike the final section of the Inca Trail</li><li>Visit Wiñay Wayna ruins</li><li>Arrive at Machu Picchu via Sun Gate</li><li>Full day at Machu Picchu (Day 2)</li><li>Perfect for limited time</li></ul>',
            'days' => 2,
            'duration' => '2 days / 1 night',
            'group_size' => 16,
            'activity_level' => 'high',
            'physical_difficulty' => 'moderate_demanding',
            'cultural_rating' => 5,
            'wildlife_expectation' => 3,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '04:00 a.m. (Day 1)',
            'return_time' => '10:00 p.m. (Day 2)',
            'spaces_available' => 'specific_dates',
            'price_from' => 520,
            'price_normal' => 600,
            'price_offer' => 520,
            'per_person' => 1,
            'active_promotion' => 1,
            'promo_tag' => 'LIMITED TIME',
            'promo_color' => '#a29bfe',
            'meta_title' => 'Short Inca Trail 2 Days to Machu Picchu - Quick Trek',
            'meta_description' => 'Hike the Inca Trail in 2 days. Perfect for limited time. Includes Wiñay Wayna and Machu Picchu.',
            'focus_keyword' => 'short inca trail',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['may', 'jun', 'jul', 'aug', 'sep'],
            'location_names' => ['Inca Trail', 'Machu Picchu'],
        ],
        'taxonomies' => [
            'package_type' => ['Trekking', 'Multi-day'],
            'interest' => ['Adventure', 'History', 'Nature'],
            'locations' => ['Cusco', 'Inca Trail', 'Machu Picchu'],
        ],
    ],

    // ========================================
    // ADVENTURE TOURS - 3 tours
    // ========================================

    // 15. White Water Rafting
    [
        'title' => 'White Water Rafting Urubamba River - Full Day',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.6,
            'service_type' => 'shared',
            'summary' => 'Experience thrilling class III-IV rapids on the Urubamba River in the heart of the Sacred Valley.',
            'description' => '<p>Get your adrenaline pumping on this full-day white water rafting adventure on the Urubamba River. Navigate exciting class III and IV rapids with names like "Chuquicahuana" and "5 Bends" while enjoying stunning Sacred Valley scenery.</p><p>Perfect for adventure seekers with some rafting experience. All safety equipment and professional guides included.</p>',
            'included' => '<ul><li>Professional rafting guide</li><li>All safety equipment (helmet, life jacket, paddle)</li><li>Wetsuit and splash jacket</li><li>Transportation from Cusco</li><li>Lunch</li><li>First aid kit</li></ul>',
            'not_included' => '<ul><li>Breakfast</li><li>Travel insurance</li><li>Tips</li><li>Waterproof camera</li></ul>',
            'highlight' => '<ul><li>Class III-IV rapids</li><li>Sacred Valley scenery</li><li>Professional safety team</li><li>Lunch included</li><li>No experience required</li></ul>',
            'days' => 1,
            'duration' => '1 day (8 hours)',
            'group_size' => 20,
            'activity_level' => 'very_high',
            'physical_difficulty' => 'moderate_demanding',
            'cultural_rating' => 1,
            'wildlife_expectation' => 2,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '07:00 a.m.',
            'return_time' => '04:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 65,
            'price_normal' => 85,
            'price_offer' => 65,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'White Water Rafting Sacred Valley - Urubamba River',
            'meta_description' => 'Class III-IV white water rafting on the Urubamba River. Full day adventure from Cusco.',
            'focus_keyword' => 'white water rafting peru',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Sacred Valley'],
        ],
        'taxonomies' => [
            'package_type' => ['Adventure', 'Full Day Tour'],
            'interest' => ['Adventure', 'Nature'],
            'locations' => ['Sacred Valley', 'Urubamba'],
        ],
    ],

    // 16. Mountain Biking Sacred Valley
    [
        'title' => 'Mountain Biking Sacred Valley - Downhill Adventure',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.4,
            'service_type' => 'shared',
            'summary' => 'Thrilling downhill mountain biking from 4,350m to the Sacred Valley floor, passing through remote Andean villages.',
            'description' => '<p>Experience an exhilarating mountain biking adventure starting at Abra Málaga pass (4,350m) and descending through diverse ecosystems to the Sacred Valley. Ride through cloud forests, past waterfalls, and through traditional Andean villages.</p><p>This mostly downhill route offers stunning views and an adrenaline-filled day suitable for riders with basic biking experience.</p>',
            'included' => '<ul><li>Professional guide</li><li>Quality mountain bike</li><li>Safety equipment (helmet, gloves, pads)</li><li>Support vehicle</li><li>Lunch</li><li>Transportation</li></ul>',
            'not_included' => '<ul><li>Breakfast and dinner</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Downhill from 4,350m</li><li>40km of thrilling biking</li><li>Cloud forest scenery</li><li>Remote Andean villages</li><li>Support vehicle included</li></ul>',
            'days' => 1,
            'duration' => '1 day (9 hours)',
            'group_size' => 12,
            'activity_level' => 'high',
            'physical_difficulty' => 'moderate',
            'cultural_rating' => 3,
            'wildlife_expectation' => 3,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '06:00 a.m.',
            'return_time' => '05:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 75,
            'price_normal' => 95,
            'price_offer' => 75,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Mountain Biking Sacred Valley - Downhill Adventure Peru',
            'meta_description' => 'Thrilling downhill mountain biking from 4,350m. 40km through Sacred Valley and cloud forest.',
            'focus_keyword' => 'mountain biking peru',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Sacred Valley'],
        ],
        'taxonomies' => [
            'package_type' => ['Adventure', 'Full Day Tour'],
            'interest' => ['Adventure', 'Nature'],
            'locations' => ['Sacred Valley', 'Abra Málaga'],
        ],
    ],

    // 17. Zip-lining & Via Ferrata
    [
        'title' => 'Zip-lining & Via Ferrata Sacred Valley Adventure',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.5,
            'service_type' => 'shared',
            'summary' => 'Soar through the Sacred Valley on thrilling zip-lines and climb via ferrata routes with spectacular mountain views.',
            'description' => '<p>Experience the ultimate adrenaline rush with a combination of zip-lining and via ferrata climbing in the heart of the Sacred Valley. Fly over the valley on 6 zip-lines, including the longest at 500 meters, then climb via ferrata routes on vertical rock faces.</p><p>This adventure offers an unforgettable perspective of the Sacred Valley with safety as our top priority.</p>',
            'included' => '<ul><li>Professional guide</li><li>All safety equipment</li><li>Transportation from Cusco</li><li>Lunch</li><li>Insurance</li></ul>',
            'not_included' => '<ul><li>Breakfast and dinner</li><li>Tips</li><li>Photos and videos</li></ul>',
            'highlight' => '<ul><li>6 zip-lines up to 500m long</li><li>Via ferrata rock climbing</li><li>Spectacular valley views</li><li>Professional safety team</li><li>Lunch included</li></ul>',
            'days' => 1,
            'duration' => '1 day (7 hours)',
            'group_size' => 16,
            'activity_level' => 'high',
            'physical_difficulty' => 'moderate',
            'cultural_rating' => 1,
            'wildlife_expectation' => 2,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '08:00 a.m.',
            'return_time' => '04:00 p.m.',
            'spaces_available' => 'daily',
            'price_from' => 85,
            'price_normal' => 110,
            'price_offer' => 85,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Zip-lining & Via Ferrata Sacred Valley - Adventure Tour',
            'meta_description' => 'Thrilling zip-line and via ferrata adventure in the Sacred Valley. 6 zip-lines and rock climbing.',
            'focus_keyword' => 'zip lining peru',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Sacred Valley'],
        ],
        'taxonomies' => [
            'package_type' => ['Adventure', 'Full Day Tour'],
            'interest' => ['Adventure'],
            'locations' => ['Sacred Valley', 'Pachar'],
        ],
    ],

    // ========================================
    // COMBINED TOURS - 3 tours
    // ========================================

    // 18. Cusco & Machu Picchu 3 Days
    [
        'title' => 'Cusco & Machu Picchu 3 Days - Express Package',
        'data' => [
            'featured_package' => 1,
            'rating' => 4.6,
            'tripadvisor_rating' => 4.7,
            'total_reviews' => 2156,
            'tripadvisor_url' => 'https://www.tripadvisor.com/Attraction_Review-g294314-d77889900-Cusco_Machu_Picchu_3_Days-Cusco_Cusco_Region.html',
            'service_type' => 'private',
            'summary' => 'Perfect introduction to Cusco and Machu Picchu in 3 days. City tour, Sacred Valley, and the Lost City of the Incas.',
            'description' => '<p>Experience the highlights of Cusco and Machu Picchu on this express 3-day package. Perfect for travelers with limited time who want to see the essentials.</p><p>Day 1: Cusco city tour and nearby ruins. Day 2: Sacred Valley full day tour. Day 3: Machu Picchu full day tour by train.</p>',
            'included' => '<ul><li>2 nights hotel in Cusco (3-star)</li><li>Private transportation</li><li>Professional guide</li><li>All entrance fees</li><li>Train tickets to Machu Picchu</li><li>2 breakfasts, 1 lunch</li></ul>',
            'not_included' => '<ul><li>First breakfast, dinners</li><li>Travel insurance</li><li>Tips</li><li>Personal expenses</li></ul>',
            'highlight' => '<ul><li>Cusco city tour</li><li>Sacred Valley highlights</li><li>Machu Picchu guided tour</li><li>Private service</li><li>All logistics handled</li></ul>',
            'days' => 3,
            'duration' => '3 days / 2 nights',
            'group_size' => 8,
            'activity_level' => 'moderate',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 5,
            'wildlife_expectation' => 2,
            'departure' => 'Cusco Airport',
            'arrival' => 'Cusco Airport',
            'departure_time' => 'Flexible',
            'return_time' => 'Flexible',
            'spaces_available' => 'daily',
            'price_from' => 420,
            'price_normal' => 520,
            'price_offer' => 420,
            'per_person' => 1,
            'active_promotion' => 1,
            'promo_tag' => 'EXPRESS',
            'promo_color' => '#00b894',
            'meta_title' => 'Cusco & Machu Picchu 3 Days - Express Package Tour',
            'meta_description' => '3-day package covering Cusco highlights and Machu Picchu. Hotel, tours, and train included.',
            'focus_keyword' => 'cusco machu picchu 3 days',
            'show_on_homepage' => 1,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Cusco City Center', 'Machu Picchu'],
        ],
        'taxonomies' => [
            'package_type' => ['Multi-day', 'Package'],
            'interest' => ['Culture', 'History', 'Photography'],
            'locations' => ['Cusco', 'Sacred Valley', 'Machu Picchu'],
        ],
    ],

    // 19. Sacred Valley & Machu Picchu 2 Days
    [
        'title' => 'Sacred Valley & Machu Picchu 2 Days Tour',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.5,
            'service_type' => 'shared',
            'summary' => 'Explore the Sacred Valley and Machu Picchu in 2 action-packed days. Pisac, Ollantaytambo, and the Lost City.',
            'description' => '<p>Make the most of your time with this efficient 2-day tour combining the Sacred Valley and Machu Picchu. Day 1: Visit Pisac, Ollantaytambo, and Chinchero, overnight in Aguas Calientes. Day 2: Early visit to Machu Picchu with guided tour.</p>',
            'included' => '<ul><li>Hotel in Aguas Calientes (1 night)</li><li>Transportation</li><li>Professional guide</li><li>All entrance fees</li><li>Train tickets</li><li>1 breakfast, 1 lunch</li></ul>',
            'not_included' => '<ul><li>Dinners</li><li>Travel insurance</li><li>Tips</li></ul>',
            'highlight' => '<ul><li>Sacred Valley highlights</li><li>Overnight in Aguas Calientes</li><li>Early access to Machu Picchu</li><li>Professional guide</li><li>Great value for time</li></ul>',
            'days' => 2,
            'duration' => '2 days / 1 night',
            'group_size' => 16,
            'activity_level' => 'moderate',
            'physical_difficulty' => 'easy',
            'cultural_rating' => 5,
            'wildlife_expectation' => 2,
            'departure' => 'Cusco - Hotel pickup',
            'arrival' => 'Cusco - Hotel drop-off',
            'departure_time' => '07:00 a.m. (Day 1)',
            'return_time' => '08:00 p.m. (Day 2)',
            'spaces_available' => 'daily',
            'price_from' => 320,
            'price_normal' => 390,
            'price_offer' => 320,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Sacred Valley & Machu Picchu 2 Days - Efficient Tour',
            'meta_description' => 'Visit Sacred Valley and Machu Picchu in 2 days. Overnight in Aguas Calientes.',
            'focus_keyword' => 'sacred valley machu picchu 2 days',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Sacred Valley', 'Machu Picchu'],
        ],
        'taxonomies' => [
            'package_type' => ['Multi-day', 'Package'],
            'interest' => ['Culture', 'History'],
            'locations' => ['Sacred Valley', 'Machu Picchu', 'Aguas Calientes'],
        ],
    ],

    // 20. Amazon Jungle Tour 3 Days
    [
        'title' => 'Amazon Jungle Tour 3 Days - Manu Rainforest',
        'data' => [
            'featured_package' => 0,
            'rating' => 4.7,
            'service_type' => 'shared',
            'summary' => 'Explore the pristine Amazon rainforest. Spot wildlife, visit clay licks, and experience the jungle at night.',
            'description' => '<p>Escape to the Amazon rainforest on this 3-day jungle adventure in the Manu Biosphere Reserve. Travel from the Andes to the Amazon, spotting wildlife including monkeys, macaws, caimans, and possibly jaguars.</p><p>Stay in comfortable jungle lodges, explore rainforest trails, visit parrot clay licks, and experience the magic of the jungle at night.</p>',
            'included' => '<ul><li>Expert naturalist guide</li><li>2 nights jungle lodge</li><li>All meals during tour</li><li>Transportation from Cusco</li><li>Rubber boots and rain ponchos</li><li>All activities</li></ul>',
            'not_included' => '<ul><li>First breakfast and last dinner</li><li>Travel insurance</li><li>Tips</li><li>Personal items</li></ul>',
            'highlight' => '<ul><li>Manu rainforest exploration</li><li>Parrot clay lick viewing</li><li>Night wildlife walks</li><li>Canopy tower visit</li><li>Jungle lodge accommodation</li></ul>',
            'days' => 3,
            'duration' => '3 days / 2 nights',
            'group_size' => 12,
            'activity_level' => 'moderate',
            'physical_difficulty' => 'moderate',
            'cultural_rating' => 2,
            'wildlife_expectation' => 5,
            'departure' => 'Cusco - Meeting point',
            'arrival' => 'Cusco - Meeting point',
            'departure_time' => '06:00 a.m. (Day 1)',
            'return_time' => '07:00 p.m. (Day 3)',
            'spaces_available' => 'daily',
            'price_from' => 380,
            'price_normal' => 450,
            'price_offer' => 380,
            'per_person' => 1,
            'active_promotion' => 0,
            'meta_title' => 'Amazon Jungle Tour 3 Days - Manu Rainforest Peru',
            'meta_description' => 'Explore the Amazon rainforest in Manu. Wildlife, clay licks, jungle lodge. 3 days from Cusco.',
            'focus_keyword' => 'amazon jungle tour peru',
            'show_on_homepage' => 0,

            // FASE 2
            'best_months' => ['apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct'],
            'location_names' => ['Amazon Rainforest (Tambopata)'],
            'inclusions' => [
                'Professional bilingual guide',
                'All entrance fees to Manu National Park',
                'Round-trip transportation from Cusco',
            ],
            'reviews' => [
                [
                    'author' => 'David K.',
                    'rating' => 5,
                    'date' => '2025-09-10',
                    'content' => 'Amazing wildlife! We saw monkeys, macaws, caimans and so much more. The jungle lodge was comfortable and the guides were incredibly knowledgeable.',
                    'country' => 'Australia',
                ],
                [
                    'author' => 'Lisa M.',
                    'rating' => 5,
                    'date' => '2025-08-18',
                    'content' => 'Unforgettable experience! The night walks were magical and the clay lick was spectacular. Highly recommend!',
                    'country' => 'Canada',
                ],
                [
                    'author' => 'Carlos R.',
                    'rating' => 4,
                    'date' => '2025-07-25',
                    'content' => 'Great jungle adventure. Saw tons of wildlife and learned a lot about the Amazon ecosystem. Excellent value for money.',
                    'country' => 'Spain',
                ],
            ],

            // FASE 3
            'overview' => 'Experience the magic of the Amazon rainforest on this unforgettable 3-day journey into Manu National Park. Explore pristine jungle, spot exotic wildlife including monkeys, macaws, and caimans, and learn about the delicate ecosystem from expert naturalist guides. This adventure takes you deep into one of the most biodiverse regions on Earth.',
            'quick_facts' => [
                ['icon' => 'clock', 'label' => 'Duration', 'value' => '3 days / 2 nights'],
                ['icon' => 'users', 'label' => 'Group Size', 'value' => 'Max 12 people'],
                ['icon' => 'globe', 'label' => 'Languages', 'value' => 'English, Spanish'],
                ['icon' => 'calendar', 'label' => 'Availability', 'value' => 'Year-round'],
            ],
            'highlights' => [
                'Wildlife spotting: monkeys, macaws, caimans, and more',
                'Night jungle walks to see nocturnal animals',
                'Visit to natural clay lick (collpa)',
                'Canoe trips on jungle rivers',
                'Expert naturalist guides',
                'Comfortable jungle lodge accommodation',
            ],
            'itinerary' => [
                [
                    'day_number' => 1,
                    'title' => 'Cusco to Amazon Rainforest',
                    'description' => 'Early morning departure from Cusco through the stunning cloud forest. Descend from the high Andes to the Amazon basin, passing through diverse ecosystems. Arrive at the jungle lodge in the afternoon. After settling in, take your first jungle walk to explore the surroundings and spot wildlife. Enjoy a delicious dinner and night walk to see nocturnal creatures.',
                    'meals' => 'Lunch, Dinner',
                    'accommodation' => 'Jungle Lodge',
                    'activities' => ['Scenic drive through cloud forest', 'First jungle exploration', 'Night walk'],
                ],
                [
                    'day_number' => 2,
                    'title' => 'Full Day Amazon Exploration',
                    'description' => 'Wake to the sounds of the jungle. After breakfast, take a canoe trip along the river to spot caimans, capybaras, and various bird species. Visit the macaw clay lick to see dozens of colorful parrots. In the afternoon, trek deeper into the rainforest with your guide to learn about medicinal plants and see monkeys swinging through the canopy. Evening wildlife observation.',
                    'meals' => 'Breakfast, Lunch, Dinner',
                    'accommodation' => 'Jungle Lodge',
                    'activities' => ['Canoe river trip', 'Macaw clay lick visit', 'Jungle trek', 'Wildlife spotting'],
                ],
                [
                    'day_number' => 3,
                    'title' => 'Morning Birdwatching & Return to Cusco',
                    'description' => 'Early morning birdwatching walk to catch the jungle at its most active. Return to lodge for breakfast, then pack up for the journey back to Cusco. Arrive in Cusco by late afternoon with unforgettable memories of the Amazon.',
                    'meals' => 'Breakfast, Lunch',
                    'accommodation' => 'None (return to Cusco)',
                    'activities' => ['Morning birdwatching', 'Return journey to Cusco'],
                ],
            ],
            'brochure_url' => '',
            'guide_profiles' => [],

            // FASE 4
            'departures' => [
                ['date' => '2025-05-15', 'price' => 380, 'availability' => 'available', 'spaces_available' => 12],
                ['date' => '2025-06-01', 'price' => 380, 'availability' => 'available', 'spaces_available' => 8],
                ['date' => '2025-07-01', 'price' => 450, 'availability' => 'limited', 'spaces_available' => 3],
                ['date' => '2025-08-15', 'price' => 450, 'availability' => 'sold_out', 'spaces_available' => 0],
            ],
            'inclusions_full' => [
                'Professional bilingual guide',
                'All entrance fees to Manu National Park',
                'Round-trip transportation from Cusco',
                'Hotel accommodation (2 nights)',
                'All meals (breakfast, lunch, dinner)',
                'First aid kit and oxygen',
                'Rubber boots for jungle trekking',
            ],
            'exclusions' => [
                'International flights to Peru',
                'Travel insurance',
                'Personal expenses and souvenirs',
                'Tips for guides and drivers',
                'Alcoholic beverages',
            ],
            'currency_options' => ['USD', 'EUR', 'GBP'],
            'show_price_calculator' => false,

            // FASE 5
            'contact_email' => 'info@peruviantours.com',
            'whatsapp_number' => '+51987654321',
            'contact_cta_text' => 'Book Your Amazon Adventure Today!',
            'faqs' => [
                ['question' => 'What wildlife can I expect to see?', 'answer' => 'Common sightings include monkeys (howler, spider, capuchin), macaws, toucans, caimans, capybaras, and various jungle birds. Jaguars are rare but possible.'],
                ['question' => 'What should I pack?', 'answer' => 'Light long-sleeve clothing, rain jacket, insect repellent, sunscreen, flashlight, binoculars, camera, and personal medications. We provide rubber boots.'],
                ['question' => 'Is it safe for children?', 'answer' => 'Yes, the tour is suitable for children 6+ who can handle moderate walking. Younger children should consult with us first.'],
                ['question' => 'What are the sleeping arrangements?', 'answer' => 'Comfortable jungle lodge with private rooms, mosquito nets, shared bathrooms, and common dining area.'],
            ],
            'review_platforms' => ['tripadvisor', 'google'],
            'show_review_filter' => false,

            // FASE 6
            'related_posts_manual' => [],
            'impact_title' => 'Sustainable Amazon Tourism',
            'impact_items' => [
                ['icon' => 'users', 'title' => 'Local Guides', 'description' => 'Supporting Amazonian communities'],
                ['icon' => 'leaf', 'title' => 'Conservation', 'description' => 'Protecting Manu rainforest'],
                ['icon' => 'heart', 'title' => 'Education', 'description' => 'Environmental awareness programs'],
            ],
            'impact_background' => null,
            'trust_badges' => [],
            'certifications_text' => 'Committed to Sustainable Rainforest Tourism',
        ],
        'taxonomies' => [
            'package_type' => ['Multi-day', 'Wildlife', 'Adventure'],
            'interest' => ['Wildlife', 'Nature', 'Adventure', 'Photography'],
            'locations' => ['Cusco', 'Manu', 'Amazon'],
        ],
    ],
];
