<?php
/**
 * Mock Packages Data - Phase 7A: Basic Fields Only
 * 30 complete travel packages - FASE 7A
 * 
 * Includes: WordPress native + PackageGeneral + PackageBaseInfo (simple fields only)
 * Excludes: Repeaters (highlights, guarantees), Media, Itinerary, Availability, SEO
 */

if (!defined('ABSPATH')) {
    exit;
}

return [
    // 1. CLASSIC INCA TRAIL 4D/3N
    [
        'title' => 'Classic Inca Trail 4 Days to Machu Picchu',
        'excerpt' => 'Trek the legendary Inca Trail to Machu Picchu over 4 days, following ancient pathways through stunning Andean scenery.',
        'content' => '<p>The Classic Inca Trail is Peru\'s most iconic trek. This 4-day journey follows ancient stone pathways built by the Incas, winding through cloud forests and past remarkable archaeological sites before reaching Machu Picchu at sunrise.</p>',
        
        // PackageGeneral fields
        'service_type' => 'shared',
        'rating' => 4.9,
        'stars' => 5,
        'summary' => 'Trek the world-famous Inca Trail over 4 incredible days. Cross Dead Woman\'s Pass, explore ancient ruins, and arrive at the Sun Gate for your first view of Machu Picchu.',
        'description' => '<p>The Classic Inca Trail offers one of the world\'s greatest hiking experiences. Over four days, you\'ll climb to 4,215 meters, explore Inca ruins like Wiñay Wayna, and camp under starry Andean skies.</p><p>On day four, wake early to reach the Sun Gate at sunrise for a magical first view of Machu Picchu. Our experienced guides and quality equipment ensure comfort throughout.</p>',
        'included' => '<ul><li>Professional bilingual guide</li><li>Inca Trail permits and entrance fees</li><li>All meals on trail (3B, 3L, 3D)</li><li>Camping equipment</li><li>Porters for group gear</li><li>Train tickets</li><li>Bus tickets</li></ul>',
        'not_included' => '<ul><li>Sleeping bags ($20 rental)</li><li>Walking poles ($15 rental)</li><li>Travel insurance</li><li>Personal porter ($140)</li><li>Tips</li></ul>',
        'video_url' => '',
        'package_type_slug' => 'multi-day-trek',
        'interest_slugs' => ['adventure', 'culture', 'nature'],
        'months' => ['april', 'may', 'june', 'july', 'august', 'september', 'october'],
        'fixed_departures_days' => [],
        'spot_calendar_slug' => 'inca-trail',
        'free_spot_start_day' => 1,
        'specialist_slug' => 'trekking',
        'destination_slug' => 'machu-picchu',
        'locations_slugs' => ['cusco', 'machu-picchu', 'sacred-valley'],
        'activity_level' => 'high',
        'altitude' => '4,215m / 13,828ft',
        'days' => 4,
        'physical_difficulty' => 'moderate_demanding',
        'cultural_rating' => '5',
        'wildlife_expectation' => '3',
        'optional_renting_slugs' => ['sleeping-bag', 'trekking-poles'],
        'is_prepayment' => true,
        'incatrail' => true,
        'show_on_homepage' => true,
        'optional' => false,
        'travel_zoo' => false,
        'luxury' => false,
        'show_specialist' => true,
        'recommendations' => '<p><strong>Best time:</strong> May-September. <strong>Fitness:</strong> Train 2-3 months before. <strong>Altitude:</strong> Spend 2 days in Cusco first.</p>',
        'featured_package' => true,
        'order' => 1,
        'included_services_slugs' => ['professional-guide', 'meals', 'camping-equipment'],
        'additional_info_slugs' => ['what-to-bring', 'weather-info'],
        'tag_locations_slugs' => ['cusco', 'machu-picchu'],
        'flights_slugs' => [],
        'title_overview' => 'Trip Overview',
        'title_itinerary' => 'Day by Day Itinerary',
        'title_dates' => 'Dates & Prices',
        'title_included' => 'What\'s Included',
        'title_optional_act' => 'Optional Activities',
        'title_additional_info' => 'Additional Information',
        
        // PackageBaseInfo simple fields
        'duration' => '4 days / 3 nights',
        'group_size' => 12,
        'departure' => 'Plaza de Armas, Cusco',
        'arrival' => 'Plaza de Armas, Cusco',
        'departure_time' => '05:00 a.m.',
        'return_time' => '08:00 p.m.',
        'availability' => 'specific_dates',
        'affiliate_url' => '',
        'tagline' => 'The world\'s most famous trek to the Lost City of the Incas',
        'tripadvisor_rating' => 4.9,
        'tripadvisor_url' => 'https://www.tripadvisor.com/example',
        'google_rating' => 4.8,
        'total_reviews' => 2847,
        'show_rating_badge' => true,
        'video_label' => 'Start planning your Inca Trail adventure',
        'show_reserve_later' => true,
        'show_international_standards' => true,
    ],

    // 2. SALKANTAY TREK 5D/4N
    [
        'title' => 'Salkantay Trek 5 Days to Machu Picchu',
        'excerpt' => 'Adventure through snow-capped mountains to tropical jungle on this spectacular alternative route to Machu Picchu.',
        'content' => '<p>The Salkantay Trek offers incredible landscape diversity, from glacial mountain passes to lush cloud forests.</p>',
        
        'service_type' => 'shared',
        'rating' => 4.8,
        'stars' => 5,
        'summary' => 'Trek past magnificent Salkantay Mountain (6,271m), through cloud forests and coffee plantations on this National Geographic Top 25 trek.',
        'description' => '<p>Cross Salkantay Pass at 4,650m, descend into cloud forest at Santa Teresa, soak in hot springs, and reach Aguas Calientes for Machu Picchu visit.</p>',
        'included' => '<ul><li>Expert bilingual guide</li><li>All camping equipment and meals</li><li>Machu Picchu entrance and tour</li><li>Train tickets</li><li>Bus service</li><li>Horses for group equipment</li></ul>',
        'not_included' => '<ul><li>Sleeping bag ($20)</li><li>Poles ($15)</li><li>Insurance</li><li>Hot springs ($3)</li><li>Tips</li></ul>',
        'video_url' => '',
        'package_type_slug' => 'multi-day-trek',
        'interest_slugs' => ['adventure', 'nature', 'photography'],
        'months' => ['april', 'may', 'june', 'july', 'august', 'september', 'october'],
        'fixed_departures_days' => ['monday', 'wednesday', 'friday'],
        'spot_calendar_slug' => 'salkantay',
        'free_spot_start_day' => 1,
        'specialist_slug' => 'trekking',
        'destination_slug' => 'machu-picchu',
        'locations_slugs' => ['cusco', 'machu-picchu'],
        'activity_level' => 'high',
        'altitude' => '4,650m / 15,255ft',
        'days' => 5,
        'physical_difficulty' => 'difficult',
        'cultural_rating' => '4',
        'wildlife_expectation' => '4',
        'optional_renting_slugs' => ['sleeping-bag', 'trekking-poles'],
        'is_prepayment' => true,
        'incatrail' => false,
        'show_on_homepage' => true,
        'optional' => false,
        'travel_zoo' => false,
        'luxury' => false,
        'show_specialist' => true,
        'recommendations' => '<p>More challenging than Inca Trail. Good physical preparation essential.</p>',
        'featured_package' => true,
        'order' => 2,
        'included_services_slugs' => ['professional-guide', 'meals', 'camping-equipment'],
        'additional_info_slugs' => ['what-to-bring', 'weather-info'],
        'tag_locations_slugs' => ['cusco', 'machu-picchu'],
        'flights_slugs' => [],
        'title_overview' => 'Trek Overview',
        'title_itinerary' => 'Daily Itinerary',
        'title_dates' => 'Dates & Prices',
        'title_included' => 'Inclusions',
        'title_optional_act' => 'Optional Add-ons',
        'title_additional_info' => 'Important Information',
        
        'duration' => '5 days / 4 nights',
        'group_size' => 12,
        'departure' => 'Hotel in Cusco',
        'arrival' => 'Hotel in Cusco',
        'departure_time' => '04:30 a.m.',
        'return_time' => '07:30 p.m.',
        'availability' => 'weekly',
        'affiliate_url' => '',
        'tagline' => 'National Geographic\'s Top 25 trek through Peru\'s most diverse landscapes',
        'tripadvisor_rating' => 4.8,
        'tripadvisor_url' => '',
        'google_rating' => 4.7,
        'total_reviews' => 1523,
        'show_rating_badge' => true,
        'video_label' => 'Virtual tour of Salkantay Trek',
        'show_reserve_later' => true,
        'show_international_standards' => true,
    ],
];
