<?php
namespace Aurora\ACFKit\FieldGroups;

use Aurora\ACFKit\Core\FieldGroup;

class PackageItinerary extends FieldGroup
{
    public function register(): void
    {
        if (!function_exists('acf_add_local_field_group')) return;

        acf_add_local_field_group([
            'key' => 'group_package_itinerary',
            'title' => '🗓️ Package - Itinerary (Day by Day)',
            'fields' => [

                // ===== ITINERARY REPEATER =====
                [
                    'key' => 'field_package_itinerary',
                    'label' => '📅 Daily Itinerary',
                    'name' => 'itinerary',
                    'type' => 'repeater',
                    'instructions' => 'Day-by-day schedule of the package. Maximum 38 days.',
                    'required' => 0,
                    'min' => 0,
                    'max' => 38,
                    'layout' => 'block',
                    'button_label' => 'Add Day',
                    'collapsed' => 'field_itinerary_day_title',
                    'sub_fields' => [
                        [
                            'key' => 'field_itinerary_day_active',
                            'label' => 'Active',
                            'name' => 'active',
                            'type' => 'true_false',
                            'instructions' => 'Enable or disable this day in the itinerary.',
                            'required' => 0,
                            'default_value' => 1,
                            'ui' => 1,
                            'wrapper' => ['width' => 15],
                        ],
                        [
                            'key' => 'field_itinerary_day_order',
                            'label' => 'Day',
                            'name' => 'order',
                            'type' => 'number',
                            'instructions' => 'Day number (1-38).',
                            'required' => 0,
                            'default_value' => 1,
                            'min' => 1,
                            'max' => 38,
                            'prepend' => 'Day',
                            'wrapper' => ['width' => 15],
                        ],
                        [
                            'key' => 'field_itinerary_day_limit',
                            'label' => 'Limit',
                            'name' => 'limit',
                            'type' => 'number',
                            'instructions' => 'Participant limit for this day.',
                            'required' => 0,
                            'min' => 0,
                            'wrapper' => ['width' => 15],
                        ],
                        [
                            'key' => 'field_itinerary_day_title',
                            'label' => 'Subtitle / Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Day title or subtitle. Example: "Arrival to Cusco" or "Machu Picchu Tour"',
                            'required' => 0,
                            'maxlength' => 150,
                            'placeholder' => 'Arrival to Cusco',
                            'wrapper' => ['width' => 55],
                        ],
                        [
                            'key' => 'field_itinerary_day_content',
                            'label' => 'Daily Description',
                            'name' => 'content',
                            'type' => 'wysiwyg',
                            'instructions' => 'Complete description of activities for this day.',
                            'required' => 0,
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                        ],
                        [
                            'key' => 'field_itinerary_day_gallery',
                            'label' => '🖼️ Gallery',
                            'name' => 'gallery',
                            'type' => 'gallery',
                            'instructions' => 'Photo gallery for this day.',
                            'required' => 0,
                            'min' => 0,
                            'max' => 20,
                            'insert' => 'append',
                            'library' => 'all',
                            'preview_size' => 'medium',
                        ],
                        [
                            'key' => 'field_itinerary_day_accommodation',
                            'label' => '🏨 Accommodation',
                            'name' => 'accommodation',
                            'type' => 'text',
                            'instructions' => 'Hotel or accommodation for this night.',
                            'required' => 0,
                            'maxlength' => 100,
                            'placeholder' => 'Hotel in Cusco',
                            'wrapper' => ['width' => 40],
                        ],
                        [
                            'key' => 'field_itinerary_day_altitude',
                            'label' => '⛰️ Altitude (m)',
                            'name' => 'altitude',
                            'type' => 'number',
                            'instructions' => 'Maximum altitude reached this day (in meters).',
                            'required' => 0,
                            'min' => 0,
                            'step' => 1,
                            'append' => 'm',
                            'wrapper' => ['width' => 30],
                        ],
                        [
                            'key' => 'field_itinerary_day_optional_activities',
                            'label' => '🎯 Optional Activities',
                            'name' => 'optional_activities',
                            'type' => 'taxonomy',
                            'instructions' => 'Select optional or additional activities available this day.',
                            'required' => 0,
                            'taxonomy' => 'activity',
                            'field_type' => 'multi_select',
                            'allow_null' => 1,
                            'add_term' => 1,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'multiple' => 1,
                            'wrapper' => ['width' => 30],
                        ],

                        // ===== ITEMS REPEATER =====
                        [
                            'key' => 'field_itinerary_day_items',
                            'label' => '📋 Items (Services & Experiences)',
                            'name' => 'items',
                            'type' => 'repeater',
                            'instructions' => 'Services and experiences included in this day.',
                            'required' => 0,
                            'min' => 0,
                            'max' => 20,
                            'layout' => 'table',
                            'button_label' => 'Add Item',
                            'collapsed' => 'field_itinerary_item_text',
                            'sub_fields' => [
                                [
                                    'key' => 'field_itinerary_item_order',
                                    'label' => 'Order',
                                    'name' => 'order',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'default_value' => 1,
                                    'min' => 1,
                                    'wrapper' => ['width' => 10],
                                ],
                                [
                                    'key' => 'field_itinerary_item_type_service',
                                    'label' => 'Type Service',
                                    'name' => 'type_service',
                                    'type' => 'taxonomy',
                                    'instructions' => '',
                                    'required' => 0,
                                    'taxonomy' => 'type_service',
                                    'field_type' => 'select',
                                    'allow_null' => 1,
                                    'add_term' => 1,
                                    'save_terms' => 0,
                                    'load_terms' => 0,
                                    'return_format' => 'id',
                                    'wrapper' => ['width' => 20],
                                ],
                                [
                                    'key' => 'field_itinerary_item_text',
                                    'label' => 'Text',
                                    'name' => 'text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'maxlength' => 200,
                                    'placeholder' => 'Description',
                                    'wrapper' => ['width' => 30],
                                ],
                                [
                                    'key' => 'field_itinerary_item_hotel',
                                    'label' => 'Hotel',
                                    'name' => 'hotel',
                                    'type' => 'taxonomy',
                                    'instructions' => '',
                                    'required' => 0,
                                    'taxonomy' => 'hotel',
                                    'field_type' => 'select',
                                    'allow_null' => 1,
                                    'add_term' => 1,
                                    'save_terms' => 0,
                                    'load_terms' => 0,
                                    'return_format' => 'id',
                                    'wrapper' => ['width' => 20],
                                ],
                                [
                                    'key' => 'field_itinerary_item_alternative_hotels',
                                    'label' => 'Alternative Hotels',
                                    'name' => 'alternative_hotels',
                                    'type' => 'taxonomy',
                                    'instructions' => '',
                                    'required' => 0,
                                    'taxonomy' => 'hotel',
                                    'field_type' => 'multi_select',
                                    'allow_null' => 1,
                                    'add_term' => 1,
                                    'save_terms' => 0,
                                    'load_terms' => 0,
                                    'return_format' => 'id',
                                    'multiple' => 1,
                                    'wrapper' => ['width' => 20],
                                ],
                            ],
                        ],
                    ],
                ],

            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'package',
                    ],
                ],
            ],
            'menu_order' => 40,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
        ]);
    }
}
